# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  # Parallels specific Ubuntu 14.04 Vagrant box
  #config.vm.box = "parallels/ubuntu-14.04"

  config.vm.synced_folder "salt/roots/", "/srv/"
  config.vm.network "forwarded_port", guest: 5000, host: 5050
  config.vm.network "forwarded_port", guest: 5417, host: 5417
  config.vm.network "forwarded_port", guest: 8001, host: 8051
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder "../", "/opt/saltpad-dev"

  # VirtualBox provider specifics
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
  end

  # Parallels provider specifics
  #config.vm.provider "parallels" do |prl|
  #  prl.memory = 1024
  #  prl.cpus = 2
  #end

  # VMWare provider specifics
  #config.vm.provider "vmware_fusion" do |v|
  #  v.vmx["memsize"] = "1024"
  #  v.vmx["numvcpus"] = "2"
  #end

  config.vm.provision :salt do |salt|
    salt.install_master = true
    salt.install_type = "git"
    # salt.install_args = "v2014.1.13"
    salt.minion_config = "salt/minion"
    salt.minion_key = "salt/key/minion.pem"
    salt.minion_pub = "salt/key/minion.pub"
    salt.master_config = "salt/master"
    salt.run_highstate = true
    salt.seed_master = { "local.local" => "salt/key/minion.pub" }
    salt.bootstrap_options = "-P"
  end
  # config.vm.provision "shell", inline: "sudo salt-call state.highstate"

end
