# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder "salt/roots/", "/srv/"
  config.vm.network "forwarded_port", guest: 5000, host: 5050

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision :salt do |salt|
    salt.install_master = true
    # salt.install_type = "git"
    # salt.install_args = "v2014.1.13"
    salt.minion_config = "salt/minion"
    salt.minion_key = "salt/key/minion.pem"
    salt.minion_pub = "salt/key/minion.pub"
    salt.master_config = "salt/master"
    salt.run_highstate = false
    salt.seed_master = { "local.local" => "salt/key/minion.pub" }
  end
  config.vm.provision "shell", inline: "sudo salt-call state.highstate"

end
